fixed script

diff --git a/scripts/userctl_01_check_ip_ban_ddos_fail2ban.yaml b/scripts/userctl_01_check_ip_ban_ddos_fail2ban.yaml
--- a/scripts/userctl_01_check_ip_ban_ddos_fail2ban.yaml
+++ b/scripts/userctl_01_check_ip_ban_ddos_fail2ban.yaml
@@ -15,4 +15,8 @@ content: |
       echo "Совпадений в ddos_detect.log не найдено"
   fi
   echo "====="
-  run bash -c 'sudo /usr/local/bin/sup_exec grep --color=always -F "$1" /var/log/fail2ban.log | tail -n 5' _ "$IP" || true
+  if run sudo /usr/local/bin/sup_exec grep -q -F "$1" /var/log/fail2ban.log; then
+      run bash -c 'sudo /usr/local/bin/sup_exec grep --color=always -F "$1" /var/log/fail2ban.log | tail -n 5' _ "$IP" || true
+  else
+      echo "Совпадений в fail2ban не найдено"
+  fi
