fixed script

diff --git a/scripts/userctl_01_check_ip_ban_ddos_fail2ban.yaml b/scripts/userctl_01_check_ip_ban_ddos_fail2ban.yaml
--- a/scripts/userctl_01_check_ip_ban_ddos_fail2ban.yaml
+++ b/scripts/userctl_01_check_ip_ban_ddos_fail2ban.yaml
@@ -10,13 +10,13 @@ content: |
   run sudo /usr/local/bin/userctl fw list "$IP" || true
   echo "====="
   if run sudo /usr/local/bin/sup_exec grep -q -F "$IP" /var/log/ddos_detect.log; then
-      run bash -c 'sudo /usr/local/bin/sup_exec grep --color=always -F "$1" /var/log/ddos_detect.log | tail -n 5' _ "$IP" || true
+      run bash -c "sudo /usr/local/bin/sup_exec grep --color=always -F \"$IP\" /var/log/ddos_detect.log | tail -n 5" _ "$IP" || true
   else
       echo "Совпадений в ddos_detect.log не найдено"
   fi
   echo "====="
-  if run sudo /usr/local/bin/sup_exec grep -q -F "$1" /var/log/fail2ban.log; then
-      run bash -c 'sudo /usr/local/bin/sup_exec grep --color=always -F "$1" /var/log/fail2ban.log | tail -n 5' _ "$IP" || true
+  if run sudo /usr/local/bin/sup_exec grep -q -F "$IP" /var/log/fail2ban.log; then
+      run bash -c "sudo /usr/local/bin/sup_exec grep --color=always -F \"$1\" /var/log/fail2ban.log | tail -n 5" _ "$IP" || true
   else
-      echo "Совпадений в fail2ban не найдено"
+      echo "Совпадений в fail2ban.log не найдено"
   fi
